### ISSUE TITLE
workspaces

### ISSUE THREAD

**Issue by idkjs** [pesy/samples#2]
In pesy samples [cNames](https://github.com/pesy/samples/blob/master/cNames/package.json) there is this line:https://github.com/pesy/samples/blob/785547b692bb8583ab1e02fe0f8efa1031a7ec74/foreign-stubs/package.json#L35

What exactly is that doing and if you needed it, how would you set that up?

Thank you, sir!

**Comment by ManasJayanth** [comment]
Ah, this slipped through the review.

Well, `link:` is just a way to ask esy to use a local path as the package source. It has very little to do with pesy itself.

Docs: https://esy.sh/docs/en/linking-workflow.html#docsNav

@melwyn95  We need to remove the hardcoded path :D

**Comment by idkjs** [comment]
Would not be bad to show how its done and why it might matter, anyway. More info! Thanks for this repo, had not seen it before yesterday.
